#!/usr/bin/env php
<?php
if (isset($GLOBALS['_composer_autoload_path'])) {
    require_once $GLOBALS['_composer_autoload_path'];
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

use Composer\InstalledVersions;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Logger\ConsoleLogger;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;
use Xepozz\TestIt\Config;
use Xepozz\TestIt\TestGenerator;
use Yiisoft\Di\Container;
use Yiisoft\Di\ContainerConfig;

(new SingleCommandApplication())
    ->setName('Test it!')
    ->setVersion(InstalledVersions::getPrettyVersion('xepozz/test-it'))
    ->setDescription('A tool for generating files with tests cases based on class methods signatures.')
    ->addArgument('source', InputArgument::OPTIONAL, 'The directory that will be processed', 'src')
    ->addArgument('target', InputArgument::OPTIONAL, 'The output directory where tests will be placed', 'tests')
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $sourceDirectory = $input->getArgument('source');
        $targetDirectory = $input->getArgument('target');

        $config = new Config();
        $configFilePath = getcwd() . '/test-it.php';
        if (file_exists($configFilePath)) {
            (require_once $configFilePath)($config);
        } else {
            $config
                ->setSourceDirectory($sourceDirectory)
                ->setTargetDirectory($targetDirectory);
        }

        $logger = new ConsoleLogger($output);

        $definitions = require_once __DIR__ . '/config/container.php';
        $containerConfig = ContainerConfig::create()
            ->withDefinitions($definitions);
        $container = new Container($containerConfig);

        $generator = $container->get(TestGenerator::class);
        $generator->setLogger($logger);

        $generator->process($config);
        $output->writeln('All done.');
    })
    ->run();