on:
  pull_request:
  push:

name: "Composer unused"

jobs:
  composer-unused:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Install dependencies
        run: composer install

      - name: Run composer unused
        run: vendor/bin/composer-unused
